  kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: homeoffice-ingress
      app.kubernetes.io/component: homeoffice-ingress
      app.kubernetes.io/instance: homeoffice-ingress
    name: homeoffice-ingress
    namespace: quarkuscoffeeshop-homeoffice
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: homeoffice-ingress
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    openshift.io/generated-by: OpenShiftNewApp
  generation: 6
  labels:
    app: homeoffice-ingress
    app.kubernetes.io/component: homeoffice-ingress
    app.kubernetes.io/instance: homeoffice-ingress
  name: homeoffice-ingress
  namespace: quarkuscoffeeshop-homeoffice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: homeoffice-ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: homeoffice-ingress
    spec:
      containers:
      - env:
        - name: POSTGRESQL_JDBC_URL
          value: jdbc:postgresql://coffeeshopdb:5432/coffeeshopdb?currentSchema=coffeeshop
        - name: POSTGRESQL_USER
          value: coffeshopadmin
        - name: POSTGRESQL_PASSWORD
          value: CHANGEME
        image: image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/homeoffice-ingress:latest
        imagePullPolicy: IfNotPresent
        name: homeoffice-ingress
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

