apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source-pvc
  namespace: quarkuscoffeeshop-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
