apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkuscoffeeshop-majestic-monolith-pipeline-task-cache-pvc
  namespace: quarkuscoffeeshop-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
