apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: quarkuscoffeeshop-homeoffice-ui-build-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: quarkuscoffeeshop-homeoffice-ui-git-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: build-and-push-quarkuscoffeeshop-homeoffice-ui-$(uid)
      spec:
        pipelineRef:
          name: build-and-push-quarkuscoffeeshop-homeoffice-ui
        serviceAccountName: pipeline
        params:
          - default: changeme
            name: quay-io-account
            type: string
          - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui
            name: quay-io-repository
            type: string
          - default: latest
            name: quay-io-image-tag-name
            type: string
          - default: overlay
            name: STORAGE_DRIVER
            type: string
          - default: latest
            description: Image Tag Value
            name: IMAGE_TAG
            type: string
        resources:
          - name: app-git
            type: git
          - name: image
            type: image
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkuscoffeeshop-homeoffice-ui-webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: git-quarkuscoffeeshop-homeoffice-ui-trigger
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - name: pipeline-binding
          ref: <git-triggerbinding>
      template:
        name: quarkuscoffeeshop-homeoffice-ui-build-triggertemplate
