apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: homeoffice-ingress-git
  labels:
    app: homeoffice-ingress
spec:
  type: git
  params:
  - name: url
    value: https://github.com/quarkuscoffeeshop/homeoffice-ingress
